### ISSUE TITLE
读书中，记录一些疑问

### ISSUE THREAD

**Issue by running-db** [nauu/clickhousebook#25]
1、别字问题：正文第一页，倒数第二段落末尾处，“随着现代化终端系统对实效的要求越来越高”，此处“实效”是否应为“时效”；
2、crontab执行时间：正文第29页末尾，“在默认的情况下，每隔10秒就会”，此处是否应为每隔10分钟，分时天月周
3、正文第33页： --time那个例子，没有加--multiquery ，但是执行了2个sql

**Comment by nauu** [comment]
非常感谢你提供的勘误信息，1 和 2 确实是笔误，将会在再版中更重。 在 3 的例子中，因为是非交互式执行，所以是可以执行多条的。

**Comment by running-db** [comment]
感谢回复
