### ISSUE TITLE
老师 clickhouse数据库存储速度好像不快啊

### ISSUE THREAD

**Issue by wangxi19** [nauu/clickhousebook#32]
我在单台服务器测试, 磁盘的写入速度是150MB/S
测试插入的速度只有47MB/S, 只有磁盘IO的1/3。

是我没用对吗, 还是它只有这个速度

**Comment by wangxi19** [comment]
书我已经买了, 也看完了, 书中对存储效率方面的介绍很少。

个人建议: 整本书完结之后要有个大型实战例子就好了, 给个场景, 然后再教一教如何设计数据库解决这个实际场景, 能达到什么性能指标。

老师有空可以写一本clickhouse的进阶版

**Comment by nauu** [comment]
这个和你的硬件环境，表设计，写入方式都息息相关。
