### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by chengshiwen** [nauu/clickhousebook#37]
1. 第154页：earlies应该为earliest，为了保证新版kafka（从kafka 0.11开始）语义（虽然librdkafka做了兼容），建议把largest都改为latest（相关文字为auto.offset.reset=largest），smallest都改为earliest（相关文字为<auto_offset_reset>=smallest</auto_offset_reset>）
2. 第165页：创建spripelog_1，拼写错误，应该为stripelog_1
3. 第229页：配置文件示例，其中<node>缩进排版问题

**Comment by nauu** [comment]
感谢提供勘误信息，将在加印版本中修正
