### ISSUE TITLE
 错别字哈！

### ISSUE THREAD

**Issue by duyfgithub** [nauu/clickhousebook#44]
![0d23381cfcdf92014262a96e1bfbe1de](https://user-images.githubusercontent.com/59280831/106382737-7c1b3b80-63fc-11eb-8b3f-b9f4613fae7e.jpg)

**Comment by duyfgithub** [comment]
216页  alert delete 和 alert update

**Comment by nauu** [comment]
没看明白呀?

**Comment by dolphinsboy** [comment]
alter table not alert

**Comment by nauu** [comment]
感谢提供勘误信息~
